fix: Make sure events bubble up when calling `emit` from deeply nested child components.
`emit` works flawlessly when triggered from the direct child component. Things get worse when called from deeply nested child component. The following error pops up:

```
TypeError: undefined is not a constructor (evaluating 'handlers[i](meta)')
```

The problem is caused by assigning `handle` instead of `handle.handlers` to `eventListeners[type]`. It's a hidden bug because both `handle.length` and `handle.handlers.length` properties exist and thus when used interchangeably the javascript engine won't complain.

There is a subtle difference, though. The first one is `Function.prototype.length` which returns the number of arguments the function takes (1 for `handle`).
The second one on the other hand is `Array.prototype.length` and reports the actual number of event handlers.

The above commit fixes this problem.